# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='redis',
            field=models.IntegerField(unique=True, verbose_name='redis\u914d\u7f6e'),
        ),
    ]
