# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180416_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redisconf',
            name='index',
        ),
    ]
