# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_redisconf_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('is_type', models.IntegerField(choices=[(0, '\u5355\u673a'), (1, '\u7fa4\u96c6')], default=0, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'db_table': 'redis_group',
                'verbose_name': 'redis \u7ec4',
                'verbose_name_plural': 'redis \u7ec4',
            },
        ),
        migrations.RemoveField(
            model_name='redisconf',
            name='name',
        ),
        migrations.AddField(
            model_name='redisgroup',
            name='redis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RedisConf'),
        ),
    ]
