# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180530_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redisgroup',
            name='redis',
        ),
        migrations.AddField(
            model_name='redisconf',
            name='name',
            field=models.CharField(default=2, max_length=10, verbose_name='\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RedisGroup',
        ),
    ]
