# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180530_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisconf',
            name='type',
            field=models.IntegerField(default=0, verbose_name='\u7c7b\u578b'),
        ),
    ]
