# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationinfo',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='value'),
        ),
    ]
