# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0002_auto_20171019_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationinfo',
            name='type',
            field=models.CharField(default=1, max_length=10, verbose_name='\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
