# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0003_operationinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationinfo',
            name='key',
            field=models.CharField(db_index=True, max_length=120, verbose_name='key'),
        ),
    ]
